language: "ruby 2.6.6"
rvm:
  - 2.6.6
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec db:create
  - bundle exec db:schema:load
script:
  -  bundle exec test
  -  bundle exec test:system 
