before_script: 
  - "bundle install --jobs=3 --retry=3"
  - yarn
  - "rails db:migrate"
cache: 
  - yarn
language: "ruby 2.6.6"
rvm:
  - 2.6.6
script: 
  - "bundle exec rake test"
  - "bundle exec rake test:system"
services: 
  - postgresql
tests: 
  - rspec
