before_script: 
  - "bundle install --jobs=3 --retry=3"
  - "rails db:migrate"

language: "ruby 2.6.6"
rvm:
  - 2.6.6
script: 
  - "bundle exec rake test"
  - "bundle exec rake test:system"
services: 
  - postgresql
env:
  global:
  - COVERAGE=1
  matrix:
  - RAKE_TASK=rspec
