 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/program_directors", type: :request do
  # ProgramDirector. As you add validations to ProgramDirector, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProgramDirector.create! valid_attributes
      get program_directors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      program_director = ProgramDirector.create! valid_attributes
      get program_director_url(program_director)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_program_director_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      program_director = ProgramDirector.create! valid_attributes
      get edit_program_director_url(program_director)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProgramDirector" do
        expect {
          post program_directors_url, params: { program_director: valid_attributes }
        }.to change(ProgramDirector, :count).by(1)
      end

      it "redirects to the created program_director" do
        post program_directors_url, params: { program_director: valid_attributes }
        expect(response).to redirect_to(program_director_url(ProgramDirector.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProgramDirector" do
        expect {
          post program_directors_url, params: { program_director: invalid_attributes }
        }.to change(ProgramDirector, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post program_directors_url, params: { program_director: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested program_director" do
        program_director = ProgramDirector.create! valid_attributes
        patch program_director_url(program_director), params: { program_director: new_attributes }
        program_director.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the program_director" do
        program_director = ProgramDirector.create! valid_attributes
        patch program_director_url(program_director), params: { program_director: new_attributes }
        program_director.reload
        expect(response).to redirect_to(program_director_url(program_director))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        program_director = ProgramDirector.create! valid_attributes
        patch program_director_url(program_director), params: { program_director: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested program_director" do
      program_director = ProgramDirector.create! valid_attributes
      expect {
        delete program_director_url(program_director)
      }.to change(ProgramDirector, :count).by(-1)
    end

    it "redirects to the program_directors list" do
      program_director = ProgramDirector.create! valid_attributes
      delete program_director_url(program_director)
      expect(response).to redirect_to(program_directors_url)
    end
  end
end
